plugin: community.general.proxmox
url: "{{ lookup('ansible.builtin.env', 'PROXMOX_URL') }}"
user: "{{ lookup('ansible.builtin.env', 'PROXMOX_USER') }}"
token_id: "{{ lookup('ansible.builtin.env', 'PROXMOX_TOKEN') }}"
token_secret: "{{ lookup('ansible.builtin.env', 'PROXMOX_TOKEN_SECRET') }}"
validate_certs: true
want_facts: true
want_proxmox_nodes_ansible_host: true
compose:
  # Get the IP address of the LXC from the network configuration using ansible.utils.ipaddr
  #ansible_host: "proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ansible.utils.ipaddr"
  # Get the hostname
  ansible_host: "'{}.{}'.format(inventory_hostname, lookup('ansible.builtin.env', 'PROXMOX_DOMAIN'))"
  ansible_user: "'root' if 'node' in proxmox_type else ansible_user"
groups:
  arr: "'arr' in (proxmox_tags_parsed|list)"
  production: "'prod' in (proxmox_tags_parsed|list)"
  development: "'dev' in (proxmox_tags_parsed|list)"
  bitcoin: "'bitcoin' in (proxmox_tags_parsed|list)"
  monitoring: "'monitoring' in (proxmox_tags_parsed|list)"
  network: "'network' in (proxmox_tags_parsed|list)"
  proxmox_nodes: "'node' in proxmox_type"
  vms: "inventory_hostname.startswith('vm')"
