plugin: community.general.proxmox
url: "{{ lookup('ansible.builtin.env', 'PROXMOX_URL') }}"
user: "{{ lookup('ansible.builtin.env', 'PROXMOX_USER') }}"
token_id: "{{ lookup('ansible.builtin.env', 'PROXMOX_TOKEN') }}"
token_secret: "{{ lookup('ansible.builtin.env', 'PROXMOX_TOKEN_SECRET') }}"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: true
compose:
  #ansible_host: "proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')"
  ansible_user: "'root' if 'node' in proxmox_type else ansible_user"
groups:
  arr: "'arr' in (proxmox_tags_parsed|list)"
  bitcoin: "'bitcoin' in (proxmox_tags_parsed|list)"
  monitoring: "'monitoring' in (proxmox_tags_parsed|list)"
  network: "'network' in (proxmox_tags_parsed|list)"
  proxmox_nodes: "'node' in proxmox_type"
