---
- name: Update APT proxy configuration
  hosts: lxcs
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Update APT proxy file
      lineinfile:
        path: /etc/apt/apt.conf.d/01proxy
        line: "Acquire::http::Proxy \"{{ apt_proxy_url }}\";"
        create: yes

    - name: Remove 02proxy file if it exists
      file:
        path: /etc/apt/apt.conf.d/02proxy
        state: absent

    - name: Ensure APT cache is updated
      apt:
        update_cache: yes
