---
- name: Setup fresh LXC
  hosts: all
  become: yes

  vars:
    ssh_keys_url: "https://github.com/federicociro.keys"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist
      when: "'debian_family' in group_names"

    - name: Update and upgrade dnf packages
      dnf:
        name: '*'
        state: latest
      when: "'fedora' in group_names"

    - name: Update and upgrade yum packages
      yum:
        name: '*'
        state: latest
      when: "'redhat_family' in group_names"

    - name: Install necessary Debian packages
      apt:
        name:
          - curl
          - net-tools
          - lnav
          - tree
          - ncdu
        state: present
      when: "'debian_family' in group_names"

    - name: Install necessary Fedora packages
      dnf:
        name:
          - curl
          - net-tools
          - lnav
          - tree
          - ncdu
        state: present
      when: "'fedora' in group_names"

    - name: Install necessary CentOS/RHEL packages
      yum:
        name:
          - curl
          - net-tools
          - lnav
          - tree
          - ncdu
        state: present
      when: "'redhat_family' in group_names"

    - name: Ensure .ssh directory exists
      file:
        path: "/root/.ssh"
        state: directory
        mode: '0700'

    - name: Add SSH keys
      get_url:
        url: "{{ ssh_keys_url }}"
        dest: "/root/.ssh/authorized_keys"
        mode: '0600'

    - name: Display finishing notes
      debug:
        msg:
          - "SSH keys added."
