---
- name: Update all systems
  hosts: all
  become: yes
  tasks:
    - name: Update FreeBSD packages
      community.general.pkgng:
        name: "*"
        state: latest
      when: ansible_os_family == "FreeBSD"

    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update dnf cache (Fedora/CentOS 8+)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

    - name: Upgrade all packages (Fedora/CentOS 8+)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8
