name: Ansible Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'playbooks/**'
      - '*.yml'
      - '*.yaml'
      - '.github/workflows/ansible-lint.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'playbooks/**'
      - '*.yml'
      - '*.yaml'
      - '.github/workflows/ansible-lint.yml'

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint ./*.yml playbooks/*.yml
          
      - name: Syntax check playbooks
        run: |
          pip install ansible
          for playbook in playbooks/*.yml; do
            ansible-playbook --syntax-check $playbook || exit 1
          done