name: Ansible Playbook Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'playbooks/**'
      - 'ansible.cfg'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'playbooks/**'
      - 'ansible.cfg'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test Playbooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create test inventory
        run: |
          mkdir -p tests
          echo "[all]
          localhost ansible_connection=local
          
          [test]
          localhost ansible_connection=local" > tests/test_inventory
          
      - name: Create test vars file
        run: |
          echo "---
          # Test variables
          timezone: UTC
          packages:
            - vim
            - htop
          ssh_keys:
            - user: testuser
              key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFxu0Oalj2xQr1Zppuaax4mTM9UkJgN79x7uU/4VCVmm test@localhost
          " > tests/test_vars.yml

      - name: Test syntax for all playbooks
        run: |
          find playbooks -name "*.yml" -type f -print0 | xargs -0 -n1 ansible-playbook --syntax-check -i tests/test_inventory

      - name: Test update-all playbook
        run: ansible-playbook -i tests/test_inventory playbooks/update-all.yml --check

      - name: Test set_timezone playbook
        run: |
          ansible-playbook -i tests/test_inventory playbooks/set_timezone.yml --check -e "{'timezone': 'UTC'}"