name: Ansible Playbook Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'playbooks/**'
      - 'ansible.cfg'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'playbooks/**'
      - 'ansible.cfg'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test Playbooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint molecule molecule-docker molecule-ansible pytest-testinfra

      - name: Create test inventory
        run: |
          mkdir -p molecule/default/files
          echo "[all]
          localhost ansible_connection=local" > molecule/default/files/test_inventory

      - name: Test update-all playbook
        run: ansible-playbook -i molecule/default/files/test_inventory playbooks/update-all.yml --check --diff

      - name: Test install-packages playbook 
        run: ansible-playbook -i molecule/default/files/test_inventory playbooks/install-packages.yml --check --diff

      - name: Test set_timezone playbook
        run: ansible-playbook -i molecule/default/files/test_inventory playbooks/set_timezone.yml --check --diff